Scripts: Check existence before installing & add tig

diff --git a/dotscripts/install/all b/dotscripts/install/all
--- a/dotscripts/install/all
+++ b/dotscripts/install/all
@@ -1,15 +1,63 @@
 #!/usr/bin/env bash
 
-echo "installing diff-so-fancy"
-git clone https://github.com/so-fancy/diff-so-fancy ~/diffsofancy
-chmod +x ~/diffsofancy/diff-so-fancy
-ln -s ~/diffsofancy/diff-so-fancy ~/bin/
-echo "installing vundle"
-git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
-echo "installing vim plugins"
-vim +PluginInstall
-echo
-echo "installing tmux package manager"
-git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
-echo "remember to hit <prefix> + I to install tmux plugins"
+if ! command -v diff-so-fancy &> /dev/null; then
+    echo "installing diff-so-fancy"
+    git clone https://github.com/so-fancy/diff-so-fancy ~/local/src/diffsofancy
+    chmod +x ~/local/src/diffsofancy/diff-so-fancy
+    ln -s ~/local/src/diffsofancy/diff-so-fancy ~/local/bin/
+else
+    echo "upgrading diff-so-fancy"
+    cd ~/local/src/diffsofancy
+    git pull
+    chmod +x ~/local/src/diffsofancy/diff-so-fancy
+    ln -s ~/local/src/diffsofancy/diff-so-fancy ~/local/bin/
+    cd -
+fi
+
+if ! command -v vim &> /dev/null; then
+    echo "warning: vim not found"
+    echo "please install from your package manager and try again"
+else
+    if ! test -e ~/.vim/bundle/Vundle.vim; then
+        echo "installing vundle"
+        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
+        echo "installing vim plugins"
+        vim +PluginInstall
+    else
+        echo "upgrading vim plugins"
+        vim +PluginUpdate
+        echo "upgrading vundle"
+        vim +PluginUpgrade
+    fi
+fi
+
+if ! command -v tmux &> /dev/null; then
+    echo "warning: tmux not found"
+    echo "https://github.com/tmux/tmux/wiki"
+else
+    if ! test -e ~/.tmux/plugins/tpm; then
+        echo "installing tmux package manager"
+        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+        tmux source ~/.tmux.conf
+        echo "remember to hit <prefix> + I to install tmux plugins"
+    else
+        echo "upgrade tpm"
+        cd ~/.tmux/plugins/tpm
+        git pull
+        tmux source ~/.tmux.conf
+        cd -
+    fi
+fi
+
+if ! command -v tig &> /dev/null; then
+    echo "installing tig"
+    mkdir -p ~/local/src ~/local/bin
+    prevpwd=$PWD
+    cd ~/local/src
+    git clone https://github.com/jonas/tig
+    cd tig
+    make prefix=~/local
+    make install prefix=~/local
+    cd $prevpwd
+fi
 echo "done!"
